[package]
name = "hexsmith"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
crossterm = { version = "0.28.1", features = ["event-stream"] }
futures = "0.3.31"
portable-pty = "0.9.0"
ratatui = "0.29.0"
tokio = { version = "1.48.0", features = ["full"] }
tokio-macros = "2.6.0"
